.dockerignore
.github/workflows/fly-deploy.yml
.github/workflows/fly.yml
Dockerfile
fly.toml
package-lock.json
package.json

ci: :construction_worker: CI/CD is cool

---

nuxt.config.ts
package-lock.json
package.json

ci: :construction_worker: Ci/CD is cool for real this time

---

nuxt.config.ts
package-lock.json
package.json

Reverts RedBit-devs/RedBit#38
At this point this is just sad and i'm sad

Revert "ci: :construction_worker: Ci/CD is cool for real this time"

---

.github/workflows/azure-static-web-apps-lemon-sand-08cbb6010.yml

on-behalf-of: @Azure opensource@microsoft.com

🚀  ci: add Azure Static Web Apps workflow file

---

components/BasicShowcaseCard.vue
components/dir.vue
nuxt.config.ts
package-lock.json
package.json
pages/index.vue
types/card.d.ts

- added types and typescript
- imported Icons module

feat: ✨ Created card component

---

pages/registerPage.vue

Created register page and made some style change on th login

feat: :sparkles: Register page is done

---

assets/css/main.css
layouts/default.vue
package-lock.json
pages/index.vue

also Buttons: [#11](https://github.com/RedBit-devs/RedBit/issues/11)

Created navbar and buttons with classes

---

pages/loginPage.vue
pages/registerPage.vue

Modified the register page and changed the login page's style. Also fixed the wrapped bug

Modify register and login page 

---

composables/useToken.ts
middleware/protected.ts
pages/loginPage.vue
pages/test.vue
types/response.d.ts

Probably will need some rework at some point

feature: ✨ Login API connect to Login page

---

package-lock.json
pages/registerPage.vue

Adding the date input so we can store the users birth date
close #92

feat: :lipstick: Adding the date input

---

components/ChatFieldNavbar.vue
components/ChatInputFiled.vue
components/ChatSelector.vue
components/DiscoverServers.vue
components/ServerSelector.vue
components/UserCard.vue
layouts/chat.vue
pages/testPage.vue

Finised all the components what I wanted to do in this issue.

106 create components to the chat filed

---

nuxt.config.ts

Prisma is a weird little thing
close #137

 fix: 🐛 buttons click

---

pages/loginPage.vue
pages/resetPasswordPage.vue

Finised the password reset page. Because I made it in a small screen maybe it will look kinda akward in big screen.

157 forgot password page and link at loginpage

---

server/api/user/.get.ts

Fixed duplacated id in the get user file

fix: :adhesive_bandage: Fixed duplacated id

---

package.json
prisma/seed.ts

fix: Seeding

---

server/api/server/.put.ts

Fixed  server user connection on server creation

fix: :bug: Fixed  server user connection on server creation

---

server/api/user/.put.ts

Fixed bug when removing the password

fix: :bug: Fixed bug when removing the password

---

pages/registerPage.vue

Added error  toast to register page

feat: :sparkles: Added error  toast to register page

---

package-lock.json
server/api/user/shared/servers/[id].get.ts
server/request.http

feat: :sparkles: Added shared servers api

---

package-lock.json
server/api/user/shared/friends/[id].get.ts
server/request.http

feat: :sparkles: Added shared friends api
